### ISSUE TITLE
panic serving 127.0.0.1:58199: assignment to entry in nil map

### ISSUE THREAD

**Issue by flakes** [abrander/agento#4]
Hi,

I'm trying to get the following configuration working:

    [client]
    enabled = true
    interval = 1
    secret = "..."
    server-url = "http://127.0.0.1:12345/report"

    [server]
    secret = "..."

    [server.http]
    enabled = true
    bind = "127.0.0.1"
    port = 12345

    [server.influxdb]
    url = "http://.../"
    username = "..."
    password = "..."
    database = "..."
    retentionPolicy = "autogen"

Unfortunately it only produces the following error:

      client: agento client started, reporting to http://127.0.0.1:12345/report
      scheduler: Added localhost transport with id 34FS3BJ5Fo9XrljPvFZV
      http: panic serving 127.0.0.1:58201: assignment to entry in nil map
      goroutine 13 [running]:
      net/http.(*conn).serve.func1(0x18c292c0)
              /usr/lib/go/src/net/http/server.go:1491 +0xa2
      panic(0x854cca0, 0x18c3aa20)
              /usr/lib/go/src/runtime/panic.go:458 +0x40b
      github.com/abrander/agento/server.(*Server).sendToInflux(0x18c035e0, 0x18c54520, 0x85b907e, 0x18, 0x0, 0x0)
              /home/flakes/go/src/github.com/abrander/agento/server/server.go:61 +0x12d
      github.com/abrander/agento/server.(*Server).reportHandler(0x18c035e0, 0x18c25c20)
              /home/flakes/go/src/github.com/abrander/agento/server/server.go:119 +0x677
      github.com/abrander/agento/server.(*Server).(github.com/abrander/agento/server.reportHandler)-fm(0x18c25c20)
              /home/flakes/go/src/github.com/abrander/agento/server/server.go:35 +0x28

What am I missing? I compiled from today's master.

**Comment by abrander** [comment]
You're not missing anything ;) It's a newly introduced bug. Thanks for reporting.

Fixed in df7b146.
