### ISSUE TITLE
alerts notifications?

### ISSUE THREAD

**Issue by lakano** [abrander/agento#5]
Hi !
I would like to known if it's possible to add alerts notifications ?
Regards,

**Comment by abrander** [comment]
Hi @lakano,

Thanks for your suggestion. It should be possible, but I believe it's outside the scope of Agento.

Some people use Grafana-based alerting:
http://docs.grafana.org/alerting/rules/
http://docs.grafana.org/alerting/notifications/

PS.
I know that my other project [Gansoi](/gansoi/gansoi) will get an Agento-compatible agent that will be able to alert based on Agento provided metrics at some point in the future.

Regards,
